#!/bin/sh

if [ $(uname -n) = 'curry' ]
then
  peer=wurst-i
elif [ $(uname -n) = 'wurst' ]
then
  peer=curry-i
else
  echo "Fehler: Weder Host noch Peer bekannt." && exit 1
fi

echo "$1"|ssh -i ~/.ssh/id_dsa_nfs-mount $peer
