#!/bin/sh

case "$1" in
	start)
        # See if the device is currently mounted
        if
          mount -t nfs | grep -e " on /data/partner " >/dev/null
        then
                # Kill all processes open on filesystem
                fuser -mk /data/partner

                # Unmount the filesystem
                umount -f /data/partner
	fi
	;;
	stop)
	;;
esac

exit 0
