#!/bin/sh
read cmd

if [ $(uname -n) = 'curry' ]
then
  peer=wurst-i
elif [ $(uname -n) = 'wurst' ]
then
  peer=curry-i
else
  echo "Fehler: Weder Host noch Peer bekannt." && exit 1
fi

if [ "$cmd" = 'start' ]
then
  if ! mount | grep -e " on /data/partner " >/dev/null
  then
    mount -o rsize=8192,wsize=8192,soft $peer:/data/partner /data/partner
  fi
elif [ "$cmd" = 'stop' ]
then
  # See if the device is currently mounted
  if mount -t nfs | grep -e " on /data/partner " >/dev/null
  then
          # Kill all processes open on filesystem
          fuser -mk /data/partner

          # Unmount the filesystem
          umount -f /data/partner
  fi
fi
