#!/bin/sh
#
# to be managed by heartbeat.
# description: Mounts and unmounts the cluster filesystem
#	  
# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
RETVAL2=0

if [ $# -eq 2 ]; then
    RESOURCE=$1
    shift
fi

cd /etc/sysconfig/drbd
HOST=`hostname -s`

# See how we were called.
case "$1" in
  start)
	if [ "${RESOURCE}" != "" ]; then
	    . $RESOURCE
	    if [ ${HOST} = `echo ${MASTER_NODE} | cut -d: -f1` ]; then
		action "Becoming primary on DRBD resource %s" $RESOURCE \
		    /usr/sbin/drbdsetup $MASTER_DEVICE PRI
		RETVAL=$?
		action "Mounting shared device on %s" $MASTER_MNTPOINT \
		    mount -o sync $MASTER_MNTPOINT
		RETVAL2=$?
	    elif [ ${HOST} = `echo ${SLAVE_NODE} | cut -d: -f1` ]; then
		action "Becoming primary on DRBD resource %s" $RESOURCE \
		    /usr/sbin/drbdsetup $SLAVE_DEVICE PRI
		RETVAL=$?
		action "Mounting shared device on %s" $SLAVE_MNTPOINT \
		    mount -o sync $SLAVE_MNTPOINT
		RETVAL2=$?
	    else
		echo This machine is neither master nor slave!
		exit 1
	    fi
	    [ $RETVAL -eq 0 -a $RETVAL2 -eq 0 ] && touch \
		/var/lock/subsys/datadisk || RETVAL=1
	else
	    DEVICES=`ls drbd[0-9] 2>/dev/null`
	    for D in $DEVICES; do
		$0 $D start
	    done
	fi
	;;
  stop)
	if [ "${RESOURCE}" != "" ]; then
	    . $RESOURCE
	    if [ ${HOST} = `echo ${MASTER_NODE} | cut -d: -f1` ]; then
		action "Unmounting shared device on %s" $MASTER_MNTPOINT \
		    umount $MASTER_MNTPOINT
		RETVAL2=$?
		action "Becoming secondary on DRBD resource %s" $RESOURCE \
		    /usr/sbin/drbdsetup $MASTER_DEVICE SEC
		RETVAL=$?
	    elif [ ${HOST} = `echo ${SLAVE_NODE} | cut -d: -f1` ]; then
		action "Unmounting shared device on %s" $SLAVE_MNTPOINT \
		    umount $SLAVE_MNTPOINT
		RETVAL2=$?
		action "Becoming secondary on DRBD resource %s" $RESOURCE \
		    /usr/sbin/drbdsetup $SLAVE_DEVICE SEC
		RETVAL=$?
	    else
		echo This machine is neither master nor slave!
		exit 1
	    fi
	    [ $RETVAL -eq 0 -a $RETVAL2 -eq 0 ] && rm -f \
		/var/lock/subsys/datadisk
	else
	    DEVICES=`ls drbd[0-9] 2>/dev/null`
	    for D in $DEVICES; do
		$0 $D stop
	    done
	fi
	;;
  restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  status)
	if [ -r /proc/drbd ]; then
		cat /proc/drbd
	else
		echo "DRBD module not loaded."
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit $RETVAL
