#!/bin/sh
#
# to be managed by heartbeat.
# description: Mounts and unmounts the cluster filesystem
#	  
# Copyright (C) 1999 2000, Philipp Reisner <philipp@linuxfreak.com>.
# Initial author.
#
# Copyright (C) 2000, Fábio Olivé Leite <olive@conectiva.com.br>
# Changes to support multiple devices and different distributions.
# Changes to increase robustness and exit with proper error values.
#
# Copyright (C) 2000, Thomas Mangin <thomas.mangin@free.fr>
# Major rewrite for new sections (init,mount,umount,fsck,...)
# Added full resync from slave node option (resync)
# Better heartbeat/script integration
#
# Some ideas and inspiration from Joe Hartley <jh@brainiac.com>

# Source function library.
# Some distributions don't have it, so test and act accordingly

if [ -f /etc/rc.d/init.d/functions ]; then
        if grep success /etc/rc.d/init.d/functions > /dev/null ; then        
	       . /etc/rc.d/init.d/functions
               HAVE_SUCCESS=1
        fi
fi

if [ -z "$HAVE_SUCCESS" ]; then
	# Does not react exactly like the "functions" ones
	success() {
		echo -ne [OK]\r
	}
	failure() {
		echo -ne [FAILED]\r
	}
fi

failed()
{
	echo -n $*
	# This echo is here to allow the use of cut on the sentence with " "
	echo -n " "
	failure
	echo
}

succed()
{
	echo -n $*
	# This echo is here to allow the use of cut on the sentence with " "
	echo -n " "
	success
	echo
}

# action substitution
action()
{
	text=$1...
	#echo -n $1...
	# This echo is here to allow the use of cut on the sentence with " "
	#echo -n " "
	shift
	eval $*
	if [ $? -eq 0 ]; then
		succed $text
		return 0
	else
		failed $text
		return 1
	fi
}

if [ ! -x /usr/sbin/drbdsetup ]; then
	failed "drbdsetup not found!"
	exit 1
fi

# Check for our config directory
if [ ! -d /etc/sysconfig/drbd ]; then
	failed "configuration directory not found!"
	exit 1
fi

# Check for fuser command
if [ ! -f "`which fuser 2>/dev/null`" ]; then
	failed "$0 needs the fuser command"
	exit 1
fi

# RETVAL will work as a "stuck bit" for any error. The construct
# RV=$?
# [ $RETVAL -eq 0 ] && RETVAL=$RV
# allows us to have it stuck at 1 when some error occur, even if
# subsequent operations don't fail. Using $RV prevents us from getting
# the exit value of [ ... ]. That was a dumb one... :)

RETVAL=0	# this means there were no errors
RV=0		# in this script this is just a temporary variable
HOST=`hostname -s`
if [ $# -eq 2 ]; then
    RESOURCE=$1
    shift
fi
CONFIG="/etc/sysconfig/drbd"

# Check if the node is primary
# Param : The resource
# Return "1" or "0"
isPrimary()
{
	NUMBER=`echo $1 | cut -b5`
	return `cat /proc/drbd | grep ":Primary/" | grep "^$NUMBER" | wc -l | cut -b7`
}

# Check if the node is in a connected state
# Param : The resource
# Return "1" or "0"
isConnected()
{
	NUMBER=`echo $1 | cut -b5`
	return `cat /proc/drbd | grep "Connected" | grep "^$NUMBER" | wc -l | cut -b7`
}


# set LOCAL_DEVICE : The device to mount / umount
setLocal()
{
	LOCAL_DEVICE=""
	LOCAL_FSCK=""

	if [ "$HOST" = "`echo $MASTER_NODE | cut -d: -f1`" ]; then
		LOCAL_STATE=master
		LOCAL_DEVICE=$MASTER_DEVICE
		LOCAL_FSCK=$MASTER_FSCK
	elif [ "$HOST" = "`echo $SLAVE_NODE | cut -d: -f1`" ]; then
		LOCAL_STATE=slave
		LOCAL_DEVICE=$SLAVE_DEVICE
		LOCAL_FSCK=$SLAVE_FSCK
	else
		failed "This machine is neither master nor slave"
		exit 1
	fi
}

# Return a boolean
isMounted()
{
	[ "`mount | grep $LOCAL_DEVICE | cut -f1 -d\ `" = "$LOCAL_DEVICE" ] && \
		return 1 || return 0
}

# unmount the device set by setLocal
# $1 = RESOURCE
# $2 = LOCAL_DEVICE
# Return if the device is still mounted
rudeUnMount()
{
	isMounted $1
	MOUNTED=$?
		
	if [ $MOUNTED -eq 1 ]; then
		$0 $1 umount

		isMounted $1
		MOUNTED=$?

		if [ $MOUNTED -eq 1 ]; then
			fuser -km $2
			sleep 1
			$0 $1 umount
		fi
 
		isMounted $1
		MOUNTED=$?

		if [ $MOUNTED -eq 1 ]; then
			fuser -km -9 $2
			sleep 1
			$0 $1 umount
		fi

		isMounted $1
		MOUNTED=$?
	fi

	return $MOUNTED
}

runForAll ()
{
	pushd . > /dev/null
		cd $CONFIG
		DEVICES=`ls drbd[0-9] 2>/dev/null`
	popd > /dev/null

	for D in $DEVICES; do
		for RUN in $*; do
			$0 $D $RUN
		done
	done
}

# See how we were called.
case "$1" in
	primary)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll primary
			exit $RETVAL
		fi
		
		setLocal
		isMounted $RESOURCE

		if [ $? -eq 1 ]; then
			failed "$LOCAL_DEVICE is mounted"
			exit 1
		fi

		action "Becoming primary on DRBD resource $RESOURCE" \
			/usr/sbin/drbdsetup $LOCAL_DEVICE PRI
		RV=$?
		[ $RETVAL -eq 0 ] && RETVAL=$RV
		;;

	secondary)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll secondary
			exit $RETVAL
		fi
		
		setLocal
		isMounted $RESOURCE

		if [ $? -eq 1 ]; then
			failed "$LOCAL_DEVICE is mounted"
			exit 1
		fi

		action "Becoming secondary on DRBD resource $RESOURCE" \
			/usr/sbin/drbdsetup $LOCAL_DEVICE SEC
		RV=$?
		[ $RETVAL -eq 0 ] && RETVAL=$RV
		;;

	init)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll init
			exit $RETVAL
		fi

		setLocal

		$0 $RESOURCE $LOCAL_STATE
		RV=$?
		[ $RETVAL -eq 0 ] && RETVAL=$RV
		;;

	master)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll master
			exit $RETVAL
		fi

		isPrimary $RESOURCE
		PRIMARY=$?

		setLocal
		isMounted $RESOURCE
		MOUNTED=$?

		if [ $PRIMARY -eq 0 -a $MOUNTED -eq 0 ]; then
			$0 $RESOURCE primary && 
			$0 $RESOURCE fsck && 
			$0 $RESOURCE mount
			RV=$?
			[ $RETVAL -eq 0 ] && RETVAL=$RV
		fi
		if [ $PRIMARY -eq 1 -a $MOUNTED -eq 0 ]; then
			$0 $RESOURCE fsck && 
			$0 $RESOURCE mount
			RV=$? 
			[ $RETVAL -eq 0 ] && RETVAL=$RV
		fi
		if [ $MOUNTED -eq 1 ]; then
			succed "Already in master state : nothing to do" 
			RV=$? 
			[ $RETVAL -eq 0 ] && RETVAL=$RV
		fi
		if [ $RETVAL -ne 0 -a $PRIMARY -eq 0 ]; then
			$0 $RESOURCE secondary 
			RV=$? 
			[ $RETVAL -eq 0 ] && RETVAL=$RV
		fi
		;;

	slave)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll slave
			exit $RETVAL
		fi

		setLocal

		isMounted $RESOURCE
		MOUNTED=$?

		if [ $MOUNTED -eq 1 ]; then
			rudeUnMount $RESOURCE $LOCAL_DEVICE
			RETVAL=$?
		fi

		# Only become secondary if umount succed
		if [ $RETVAL -eq 0 ]; then
			$0 $RESOURCE secondary
			setLocal
			drbdsetup $LOCAL_DEVICE wait
			RETVAL=$?
		fi
		;;

	mount)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll mount
			exit $RETVAL
		fi

		setLocal

		isMounted $RESOURCE
		MOUNTED=$?

		if [ $MOUNTED -eq 1 ]; then 
			succed "Device on $LOCAL_DEVICE already mounted"
			exit 0
		fi

		action "Mounting shared device on $LOCAL_DEVICE" \
			mount $LOCAL_DEVICE
		RV=$?
		[ $RETVAL -eq 0 ] && RETVAL=$RV
		;;

	umount)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll umount
			exit $RETVAL
		fi

		setLocal

		isMounted $RESOURCE
		MOUNTED=$?

		if [ $MOUNTED -eq 0 ]; then
			succed "$LOCAL_DEVICE is already unmounted"
			exit 0
		fi

		action "Unmounting shared device on $LOCAL_DEVICE " \
			umount $LOCAL_DEVICE

		RV=$?
		[ $RETVAL -eq 0 ] && RETVAL=$RV
		;;

	fsck)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll fsck
			exit $RETVAL
		fi

		setLocal
		isMounted $RESOURCE
		MOUNTED=$?

		if [ $MOUNTED -eq 1 ]; then
			$0 $RESOURCE umount 
			RV=$? 
			[ $RETVAL -eq 0 ] && RETVAL=$RV
		fi

		if [ $RETVAL -eq 1 ]; then
			failed "$LOCAL_DEVICE still mounted can't check"
			exit 1
		fi

		isPrimary $RESOURCE
		if [ $? -eq 1 ]; then
			echo -n "performing fsck on $RESOURCE " 
			$LOCAL_FSCK $LOCAL_DEVICE > /dev/null 2>/dev/null
			RV=$?
			[ $RV -eq 0 -o $RV -eq 1 ] && RETVAL=0
			[ $RETVAL -eq 0 ] && success || failure
			echo
		else
			failed "Can not perform fsck on secondary $RESOURCE "
			RETVAL=1
		fi

		if [ $MOUNTED -eq 1 ]; then 
			$0 $RESOURCE mount
			RV=$?
			[ $RV -eq 0 ] && RETVAL=$RV
		fi
		;;	

	resync)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll resync
			exit $RETVAL
		fi

		isPrimary
		PRIMARY=$?

		if [ $PRIMARY -eq 0 ]; then
			# TODO:DRDB sometimes lies about its connection status !!
			isConnected
			CONNECTED=$?

			if [ $CONNECTED -eq 1 ]; then
				setLocal

				rudeUnMount $RESOURCE $LOCAL_DEVICE
				MOUNTED=$?

				if [ $MOUNTED -eq 0 ]; then
					drbdsetup $LOCAL_DEVICE repl
					RETVAL=$?
				else
					failed "unmount failed, you must have a SERIOUS problem"
				fi
			else
				failed "The node is not connected to the primary"
				RETVAL=1
			fi
		else
			failed "$LOCAL_DEVICE is primary. The command must be run from a connected slave"
			RETVAL=1
		fi
		;;
		
	start)
		if [ -n "$RESOURCE" ]; then
			$0 $RESOURCE master
		else
			$0 master
		fi
		;;

	stop)
		if [ -n "$RESOURCE" ]; then
			$0 $RESOURCE slave
		else
			$0 slave
		fi
		;;
		
	restart)
		if [ -n "$RESOURCE" ]; then
			$0 $RESOURCE stop
			$0 $RESOURCE start
		else
			$0 stop
			$0 start
		fi
		;;

	status)
		if [ -r /proc/drbd ]; then
			cat /proc/drbd
		else
			failed "DRBD module not loaded."
			RETVAL=1
		fi
		;;

	state)
		if [ -n "$RESOURCE" ]; then
			. $CONFIG/$RESOURCE
		else
			runForAll state
			exit $RETVAL
		fi

		if [ -r /proc/drbd ]; then
			isPrimary $RESOURCE
			if [ $? -eq 1 ]; then
				succed "Primary"
			else
				succed "Secondary"
			fi
		else
			failed "Error drbd not loaded"
		fi
		;;

	help)
		echo "Usage: $0 [resource] {init|master|slave|mount|umount|fsck|resync|start|stop|restart|status|state|help}"
		echo "init   : set the node as master or slave at boot time"
		echo "master : set drbd as master,fsck the volume(s) and mount it/them"
		echo "slave  : set drbd as slave, umnount the volume(s) if needed"
		echo "mount  : mount the volume(s)"
		echo "umount : unmount the volume(s)"
		echo "fsck   : fsck the volume(s)"
		echo "resync : force a full resynchronisation of the slave."
		echo "         only work on the slave"
		echo "status : display drdb status (/proc/drdb)"
		echo "state  : Return Primary or Secondary depending on the node settings"
		echo "help   : ..."
		RETVAL=1
		;;
	*)
		echo "Usage: $0 [resource] {init|master|slave|mount|umount|fsck|resync|start|stop|restart|status|state|help}"
		RETVAL=1
		;;
esac

exit $RETVAL
