FROM ubuntu:jammy

RUN apt-get update && \
	apt-get install -y \
		curl \
		diffutils \
		elfutils \
		gcc \
		gnupg \
		kmod \
		make \
		patch \
		perl \
		python3-setuptools \
	&& \
	apt-get clean && \
	cd /tmp && \
	curl -fsSL https://github.com/LINBIT/python-lbdist/archive/master.tar.gz | tar vxz && \
	( cd python-lbdist-master && python3 setup.py install ) && \
	rm -rf python-lbdist-master

COPY /drbd.tar.gz /

COPY /pkgs /pkgs

COPY /entry.sh /
ENTRYPOINT /entry.sh
