all: acmp getbm #receiver sender writetest

acmp: acmp.c
	gcc -g -o acmp acmp.c

getbm: getbm.c
	gcc -g -o getbm getbm.c

#writetest: writetest.c
#	gcc -g -o writetest writetest.c

#receiver: receiver.c
#	gcc -g -o receiver receiver.c

#sender: sender.c
#	gcc -g -o sender sender.c

clean: 
	rm -f receiver sender writetest