Source: drbd
Section: misc
Priority: extra
Maintainer: David Krovich <dkrovich@csee.wvu.edu>
Build-Depends: debhelper (>= 4), debconf-utils, sp, docbook-utils, kernel-source
Standards-Version: 3.5.10

Package: drbd-modules-(KERNEL_VERSION)
Architecture: all
Section: misc
Recommends:  dpkg-dev, kernel-package, debhelper (>= 4), debconf-utils
Description: RAID 1 over tcp/ip for Linux module source
 Drbd is a block device which is designed to build high availability
 clusters by providing a virtual shared device which keeps disks in nodes
 synchronised using TCP/IP. This simulates RAID 1 but avoiding the 
 use of uncommon hardware (shared SCSI buses or Fibre Channel). 
 It is currently limited to fail-over HA clusters.
 .
 This package contains the programs that will control the 
 drbd kernel module provided in drbd-source. You will need a clustering
 service (such as heartbeat) to fully implement it.
 .
 Homepage: http://www.drbd.org
